app/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin


""" Topic Model """
class Topic(db.Model, CRUDMixin):
  id = db.Column(db.Integer, primary_key=True, unique=True)
  name = db.Column(db.String(20))
  description = db.Column(db.String(1024))
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  
""" User Model """
class User(db.Model, CRUDMixin, UserMixin):
  id = db.Column(db.Integer, primary_key=True, unique=True)
  username = db.Column(db.String(15), unique=True)
  email = db.Column(db.String(50), unique=True)
  password = db.Column(db.String(1024))
  topics = db.relationship('Topic', backref='topic', lazy=True)

app/app.py
from . import cookies
from flask import Flask, redirect, url_for, render_template
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager
from os import environ


""" Creates a Flask app instance """
def create_app():
  app = Flask(__name__)
  app.secret_key = environ.get('SECRET_KEY')
  app.config["SQLALCHEMY_DATABASE_URI"] = environ.get('DATABASE_URL')

  register_extensions(app)
  register_blueprints(app)
  return app

""" Registers cookies blueprint """
def register_blueprints(app: Flask):
  app.register_blueprint(cookies.routes.blueprint)

""" Registers extensions for Flask app """
def register_extensions(app: Flask):
  db.init_app(app)
  migrate.init_app(app, db, compare_type=True)
  login_manager.init_app(app)

app/cookies/__init__.py
from . import routes

app/cookies/routes.py
from flask import Blueprint, render_template, redirect, request, current_app, url_for
from app.models import Topic, User
from app.config import TOPICS_PER_PAGE
from app.extensions.database import db
from flask_login import login_required, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash


list_data = {
    'shopping': {'name': 'Shopping List', 'item': 'tomatos'},
    'work': {'name': 'Work To-Dos', 'item': ['attend meeting at 12', 'practice active listening']},
    'today': {'name': 'Today', 'item': 'vacuum the house'},
}

blueprint = Blueprint('cookies', __name__)

""" Start page """
@blueprint.route('/')
def index():
  return redirect('/login')

""" List Overview """
@blueprint.route('/lists')
@login_required
def topics():
    page_number = request.args.get('page', 1, type=int)
    #all_topics = Topic.query.all()
    topics_pagination = Topic.query.paginate(page= page_number, per_page=TOPICS_PER_PAGE)
    return render_template('lists.html', topics_pagination=topics_pagination)

@blueprint.route('/lists.html')
@login_required
def lists_redirect():
   return redirect('/lists')

""" Specific List """
@blueprint.route('/lists/<id>')
@login_required
def topic(id):
    topic = Topic.query.filter_by(id=id).first_or_404()
    listname = topic.name

    listdesc = topic.description.split('\n')
    return render_template('list_items.html', listname=listname, listdesc=listdesc, id=id)

""" Edit List """
@blueprint.route('/lists/<id>/edit', methods=['GET', 'POST'])
@login_required
def editlist(id):
  topic = Topic.query.filter_by(id=id).first_or_404()
  if request.method == 'POST':
    topic.name = request.form['list-name']
    topic.description = request.form['list-items']
    db.session.commit()
    return redirect(f'/lists/{id}')

  listname = topic.name
  listdesc = topic.description.split('\n')
  return render_template('editlistform.html', listname=listname, listdesc=listdesc, id=id)

""" Delete List """
@blueprint.route('/lists/<id>/delete', methods=['POST']) 
@login_required  
def deletelist(id):
  topic = Topic.query.filter_by(id=id).first_or_404()
  topic.delete()
  return redirect('/lists')

""" Create List """
@blueprint.route('/newlist', methods=['GET', 'POST'])
@login_required
def newlist():
  if request.method == "POST":
    topic = Topic(
      name=request.form['list-name'],
      description=request.form['list-items']
    )
    topic.save()
    return redirect('/lists')
  return render_template('newlistform.html')

""" About Page """
@blueprint.route('/about')
@login_required
def about():
  return render_template('about.html')

@blueprint.route('/about.html')
@login_required
def about_redirect():
  return redirect('/about')



""" Register """
@blueprint.route('/register', methods=['GET', 'POST'])
def register():
  if request.method == 'GET':
    return render_template('users/register.html')
   
  try:
    if request.form.get('password') != request.form.get('password_confirmation'):
        return render_template('users/register.html', error='The password confirmation must match the password.')
    elif User.query.filter_by(email=request.form.get('email')).first():
        return render_template('users/register.html', error='The email address is already registered.')
    elif User.query.filter_by(email=request.form.get('username')).first():
        return render_template('users/register.html', error='The username is already registered.')
      
    user = User(
          username=request.form.get('username'),
          email=request.form.get('email'),
          password=generate_password_hash(request.form.get('password'))
    )
    user.save()

    login_user(user)
    return redirect('/lists')
  
  except Exception as error_message:
    error = error_message or 'An error occurred while creating a user. Please make sure to enter valid data.'
    return render_template('users/register.html', error=error)

""" Login """
@blueprint.route('/login', methods=['GET', 'POST'])
def login():
  if request.method == 'GET':
      return render_template('users/login.html')
  try:
    user = User.query.filter_by(email=request.form.get('email')).first()

    if not user:
      raise Exception('No user with the given email address was found.')
    elif not check_password_hash(user.password, request.form.get('password')):
      raise Exception('The password does not appear to be correct.')
      
    login_user(user)
    return redirect('/lists')
      
  except Exception as error_message:
    error = error_message or 'An error occurred while logging in. Please verify your email and password.'
    return render_template('users/login.html', error=error)
  
""" Logout """
@blueprint.get('/logout')
def logout():
  logout_user()

  return redirect('/login')

app/templates/about.html
{% extends 'base.html' %}

{% block body %}
<header>
    <nav class="heading">
        <h3> TODOIST</h3> 
        <h5> - Get Your Life Sorted </h5>
      </nav>
    <nav>
      <ul class="navigation_bar">
        <li class="nav_li"><a href="/lists">My Lists</a></li>
        <li class="nav_li">About</li>
      </ul>
    </nav>
  </header>
  <div class="about-text">

<!-- Purpose -->
    <p>
      The purpose of TODOIST is to help you organize and prioritize tasks that you need to complete. 
    </p>
    <p>
      By creating a list of tasks, you can keep track of what needs to be done, when it needs to be done, and in what order.
      Overall, the purpose of TODOIST is to help you stay organized, focused, and productive, while minimizing the risk of forgetting important tasks or falling behind on deadlines.
    </p>
    <br>
    <hr>
    <br>

<!--  Privacy Policy -->
    <p>
      At TODOIST, we take your privacy very seriously. 
      This privacy policy outlines how we collect, use, and protect your personal information when you use our app.
      <br>
      <br>
      Information we collect: 
      <br>
      When you use our app, we may collect information such as your name, email address, and other personal information that you provide to us. 
      <br>

<!-- Security measures taken -->
      We use industry-standard security measures to protect your information from unauthorized access, alteration, or destruction.
      We also limit access to your information to those employees who need it to provide you with our app.
    </p>
  </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<!-- Defines the header block, sets character encoding and page title, links to CSS stylesheet and JavaScript file, and sets favicon icon -->
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODOIST - Get Your Life Sorted</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="shortcut icon" type="image/png" href="static\images\TODOIST_favicon.ico"/>
    <script src="../static/colorPicker.js" defer></script>
  {% endblock %}
</head>
<body>
  {% block body %}{% endblock %}
  <footer>
    <br>

<!-- Checks if user authenticated, displays users email -->
    {% if current_user.is_authenticated %}
      <small>
        Logged in as {{ current_user.email }}.
    <!-- Link to logout -->
        <a href="{{ url_for('cookies.logout') }}">Logout</a>
      </small>

<!-- Allows user to select background color -->
      <div class="color-picker" >
        <div class="color-picker-green" id="color-picker-green"></div>
        <div class="color-picker-red" id="color-picker-red"></div>
        <div class="color-picker-blue" id="color-picker-blue"></div>
        <div class="color-picker-yellow" id="color-picker-yellow"></div>
      </div>
    {% endif %}
  </footer>
</body>
</html>

app/templates/editlistform.html
{% extends 'base.html' %}

{% block title %}Create New Todo-list{% endblock %}

{% block body %}
<header>
    <nav class="heading">
        <h3> TODOIST</h3> 
        <h5> - Get Your Life Sorted </h5>
      </nav>
    <nav>
      <ul class="navigation_bar">
        <li class="nav_li"><a href="/lists">My Lists</a></li>
        <li class="nav_li"><a href="/about">About</a></li>
      </ul>
    </nav>
  </header>

<!-- Form to edit existing List -->
    <form class="newlist" action="/lists/{{id}}/edit" method="post">
        <h2>Edit list:</h2>
    <!-- Input with prefilled existing name -->
        <label for="list-name">List Name:</label>
        <input type="text" id="list-name" name="list-name" value="{{listname}}" style="width: 26rem;" required>
    <!-- Textarea with prefilled existing items -->
        <label for="list-items">To-Do's:</label>
        <textarea id="list-items" name="list-items" style="width: 26rem; height: 10rem;" required>{{"\n".join(listdesc)}}</textarea>
        <small>Enter new line to create multiple items</small>
        <button type="submit">Update List</button>
    </form>
    
{% endblock %}

app/templates/list_items.html
{% extends 'base.html' %}

{% block title %}{{listname}}{% endblock %}

{% block body %}
<header>
  <nav class="heading">
      <h3> TODOIST</h3> 
      <h5> - Get Your Life Sorted </h5>
    </nav>
</header>

<!-- Button to the /lists page -->
<a href="/lists">
  <button class="backbutton" >Back</button>
</a>

<!-- Displays the name of the list -->
  <h1>{{listname}}</h1>
  
<!-- Loops and displays each item in the list  -->  
  <ul>
    {% for item in listdesc %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>

<!-- Button to the /editlist page -->
<a href="/lists/{{id}}/edit">
  <button class="editbutton">Edit</button>
</a>

<!-- Form to delete the list -->
  <form class="delete-button-form" action="/lists/{{id}}/delete" method="post">
    <input class="delete-button" type="submit" name="delete" value="Delete" />
  </form>

{% endblock %}

app/templates/lists.html
{% extends 'base.html' %}

{% block title %}Your Lists{% endblock %}

{% block body %}
  <header>
      <nav class="heading">
          <h3> TODOIST</h3> 
          <h5> - Get Your Life Sorted </h5>
        </nav>
      <nav>
        <ul class="navigation_bar">
          <li class="nav_li">My Lists</li>
          <li class="nav_li"><a href="/about">About</a></li>
        </ul>
      </nav>
    </header>

<!-- Displays user's email  -->
    <h4>{{ current_user.email }} here are your lists</h4>

<!-- Lists topics with buttons -->
  <div class="list-container">
    {% for topic in topics_pagination.items %}
    <a style="cursor: pointer" href="/lists/{{ topic.id }}">
      <button class="list_buttons">
        {{ topic.name }}
      </button>
    </a>
    {% endfor %}

<!-- Adds new list button -->
    <a style="cursor: pointer" href="/newlist">
      <button style="font-weight: bold" class="list_buttons">
        + Add New List
      </button>
    </a>
  </div>

<!-- Displays quote -->
  <p style="border-left: 4px solid #ccc; font-style: italic;">"Dreams don't work unless you do" -POPO J</p>
  <br> 

<!-- Displays pagination links -->
  <nav class="prev_next">
    {% if topics_pagination.prev_num %}
      <a href="{{ url_for('cookies.topics', page=topics_pagination.prev_num) }}">Previous Page</a>
    {% else %}
      <span>Previous Page</span>
    {% endif %}
      <span> - </span>
    {% if topics_pagination.next_num %}
      <a href="{{ url_for('cookies.topics', page=topics_pagination.next_num) }}">Next Page</a>
    {% else %}
      <span>Next Page</span>
    {% endif %}
  </nav>

  {% endblock %}

app/templates/newlistform.html
{% extends 'base.html' %}

{% block title %}Create New Todo-list{% endblock %}

{% block body %}
<header>
    <nav class="heading">
        <h3> TODOIST</h3> 
        <h5> - Get Your Life Sorted </h5>
      </nav>
    <nav>
      <ul class="navigation_bar">
        <li class="nav_li"><a href="/lists">My Lists</a></li>
        <li class="nav_li"><a href="/about">About</a></li>
      </ul>
    </nav>
  </header>

<!-- Form to create new list -->
    <form class="newlist" action="/newlist" method="post"> 
        <h2>Create a new list</h2>
        <label for="list-name">List Name:</label>
        <input type="text" id="list-name" name="list-name" style="width: 26rem;" required>
        <label for="list-items">To-Do's:</label>
        <textarea id="list-items" name="list-items" style="width: 26rem; height: 10rem;" required></textarea>
        <small>Enter new line to create multiple items</small>
        <button type="submit">Create List</button>
    </form>

    
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %} 

{% block title %}TODOIST | Login{% endblock %} 

{% block body %}
<div class="login-container">
  <br/>
  <br/>
  <img src="static/images/todoist-logo.jpg" alt="The TODOIST logo" title="The TODOIST logo" height="150" width="150"/>

<!-- Login form with email and password fields-->
  <h4>Login</h4>

  <form method="POST">
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" id="email" name="email" required />
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" id="password" name="password" required />
    </div>

    <input class="login-button" type="submit" value="Login" />
  </form>

<!-- Form Error Text -->
  {% if error %}
  <p style="color: tomato">{{ error }}</p>
  {% endif %}

<!-- Register Link -->
  <a href="/register">Not a member yet? Register here</a>
  {% endblock %}
</div>

app/templates/users/register.html
{% extends 'base.html' %}

{% block title %}TODOIST | Register{% endblock %}

{% block body %}
  <div class="login-container">
    <img src="static/images/todoist-logo.jpg" alt="The TODOIST logo" title="The TODOIST logo" height="150" width="150" style="padding-top: 6.58rem"/>

<!-- Register form with email, password and password confirmation fields-->
  <h4>Register</h4>

  <form method="POST">
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>
    </div>
  
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" name="password" id="password" 
        pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
        title="Password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, and one number."
        required>
    </div>
  
    <div class="form-group">
      <label for="password_confirmation">Password Confirmation</label>
      <input type="password" name="password_confirmation" id="password_confirmation" required>
    </div>
  
    <input type="submit" value="Register">
  </form>

<!-- Form Error Text -->
    {% if error %}
        <p style="color: tomato;">{{ error }}</p>
    {% endif %}

<!-- Login Link -->
  <a href="/login">Already a member? Login here</a>
{% endblock %}

templates/list_items.html
<!doctype html>
<html>
<head>
  <title>List Items</title>
</head>
<body>
  <h1>{{ list_name }}</h1>
  <ul>
    {% for item in items %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
</body>
</html>